### ISSUE TITLE
E-step for ZIP data

### ISSUE THREAD

**Issue by jakeoung** [fonnesbeck/Bios8366#10]
In the Expectation and Maximization notebook,

I am not sure, but can you check the following E-step 

```
     a = psi * (x == 0)
     b = (1-psi)*poisson.pmf(x, mu)
```

is correct? The following can be correct.

```
    a = (1-psi) * (x == 0)
    b = psi*poisson.pmf(x, mu)
```

**Comment by fonnesbeck** [comment]
This should be correct as written. Note the notation in the equation just above it. 

In any case, it should not matter which is psi and which is 1-psi, you will get the right answer either way, the labels will just be switched.
