### ISSUE TITLE
wrong implementation of function  "conditional".

### ISSUE THREAD

**Issue by dineshkh** [fonnesbeck/Bios8366#11]
The conditional function takes as input (x_new, x, y, params), there is no need to pass y in the function. By definition of conditional probability above conditional distribution, "x_new" represent "x" and  "x" represent "y". 

Correct implementation would be:

def conditional(x_new, x, params):
    B = exponential_cov(x_new, x, params)
    C = exponential_cov(x, x, params)
    A = exponential_cov(x_new, x_new, params)
    mu = np.linalg.inv(C).dot(B.T).T.dot(x)  // y is replace by x.
    sigma = A - B.dot(np.linalg.inv(C).dot(B.T))
    return(mu.squeeze(), sigma.squeeze())

**Comment by fonnesbeck** [comment]
I'm confident the function is correct, but I should probably change the conditional equation above to clean up the notation. As it is now, A == Sigma_x, B==Sigma_xy and C==Sigma_y. I am using y in the right place in the calculation of the conditional mean, but it is confusing.

**Comment by fonnesbeck** [comment]
Fixed in f9bb08f87d4489411b2927c408e4c91025fcf867
